export const lenguageCodes = {
    afr: "Afrikaans",
    amh: "Amharic",
    ara: "Arabic",
    arc: "Aramaic",
    aym: "Aymara",
    aze: "Azerbaijani",
    bar: "Austro-Bavarian German",
    bel: "Belarusian",
    ben: "Bengali",
    ber: "Berber",
    bis: "Bislama",
    bjz: "Belizean Creole",
    bos: "Bosnian",
    bul: "Bulgarian",
    bwg: "Chibarwe",
    cal: "Carolinian",
    cat: "Catalan",
    ces: "Czech",
    cha: "Chamorro",
    ckb: "Sorani",
    cnr: "Montenegrin",
    crs: "Seychellois Creole",
    dan: "Danish",
    deu: "German",
    div: "Maldivian",
    dzo: "Dzongkha",
    ell: "Greek",
    eng: "English",
    est: "Estonian",
    fao: "Faroese",
    fas: "Persian (Farsi)",
    fij: "Fijian",
    fil: "Filipino",
    fin: "Finnish",
    fra: "French",
    gil: "Gilbertese",
    gle: "Irish",
    glv: "Manx",
    grn: "Guaraní",
    gsw: "Swiss German",
    hat: "Haitian Creole",
    heb: "Hebrew",
    her: "Herero",
    hgm: "Khoekhoe",
    hif: "Fiji Hindi",
    hin: "Hindi",
    hmo: "Hiri Motu",
    hrv: "Croatian",
    hun: "Hungarian",
    hye: "Armenian",
    ind: "Indonesian",
    isl: "Icelandic",
    ita: "Italian",
    jam: "Jamaican Patois",
    jpn: "Japanese",
    kal: "Greenlandic",
    kat: "Georgian",
    kaz: "Kazakh",
    kck: "Kalanga",
    khi: "Khoisan",
    khm: "Khmer",
    kin: "Kinyarwanda",
    kir: "Kyrgyz",
    kon: "Kikongo",
    kor: "Korean",
    kwn: "Kwangali",
    lao: "Lao",
    lat: "Latin",
    lav: "Latvian",
    lin: "Lingala",
    lit: "Lithuanian",
    loz: "Lozi",
    ltz: "Luxembourgish",
    lua: "Tshiluba",
    mah: "Marshallese",
    mey: "Hassaniya",
    mfe: "Mauritian Creole",
    mkd: "Macedonian",
    mlg: "Malagasy",
    mlt: "Maltese",
    mon: "Mongolian",
    mri: "Māori",
    msa: "Malay",
    mya: "Burmese",
    nau: "Nauru",
    nbl: "Southern Ndebele",
    ndc: "Ndau",
    nde: "Northern Ndebele",
    ndo: "Ndonga",
    nep: "Nepali",
    nfr: "Guernésiais",
    niu: "Niuean",
    nld: "Dutch",
    nno: "Norwegian Nynorsk",
    nob: "Norwegian Bokmål",
    nor: "Norwegian",
    nrf: "Jèrriais",
    nso: "Northern Sotho",
    nya: "Chewa",
    nzs: "New Zealand Sign Language",
    pap: "Papiamento",
    pau: "Palauan",
    pih: "Norfuk",
    pol: "Polish",
    por: "Portuguese",
    pov: "Upper Guinea Creole",
    prs: "Dari",
    pus: "Pashto",
    que: "Quechua",
    rar: "Cook Islands Māori",
    roh: "Romansh",
    ron: "Romanian",
    run: "Kirundi",
    rus: "Russian",
    sag: "Sango",
    sin: "Sinhala",
    slk: "Slovak",
    slv: "Slovene",
    smi: "Sami",
    smo: "Samoan",
    sna: "Shona",
    som: "Somali",
    sot: "Sotho",
    spa: "Spanish",
    sqi: "Albanian",
    srp: "Serbian",
    ssw: "Swazi",
    swa: "Swahili",
    swe: "Swedish",
    tam: "Tamil",
    tet: "Tetum",
    tgk: "Tajik",
    tha: "Thai",
    tir: "Tigrinya",
    tkl: "Tokelauan",
    toi: "Tonga",
    ton: "Tongan",
    tpi: "Tok Pisin",
    tsn: "Tswana",
    tso: "Tsonga",
    tuk: "Turkmen",
    tur: "Turkish",
    tvl: "Tuvaluan",
    ukr: "Ukrainian",
    urd: "Urdu",
    uzb: "Uzbek",
    ven: "Venda",
    vie: "Vietnamese",
    xho: "Xhosa",
    zdj: "Comorian",
    zho: "Chinese",
    zib: "Zimbabwean Sign Language",
    zul: "Zulu",
};